services:
  - type: web
    name: multimedia-site
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn multimedia_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DJANGO_DEBUG
        value: true
      - key: DJANGO_ALLOWED_HOSTS
        value: 127.0.0.1,localhost
      - key: DATABASE_URL
        value: postgresql://multimedia_user:siGoqkdRQtff3Z1jwwa3Nh5DkLL4QlXT@dpg-d05c28a4d50c73et5iq0-a.oregon-postgres.render.com/multimedia_db_630h
